In [118]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error
from sklearn.model_selection import train_test_split

In [119]:
df = pd.read_csv('../Data/PGH/DemandPrediction/ml_df.csv')
df = df.drop(columns=['Unnamed: 0'])
df.head(5)

total_households median_hh_income  mean_hh_income  population_16yrs+  \
0              1306            67409           69254               2660   
1              1306            67409           69254               2660   
2              1306            67409           69254               2660   
3              1306            67409           69254               2660   
4              1306            67409           69254               2660   

   in_labor_force  civ_labor_force  employed  unemployed  perc_employed  \
0            1845             1816      1688         128       0.634586   
1            1845             1816      1688         128       0.634586   
2            1845             1816      1688         128       0.634586   
3            1845             1816      1688         128       0.634586   
4            1845             1816      1688         128       0.634586   

   perc_unemployed  ...  wfh  mean_travel_time_to_work  perc_public  \
0          0.04812  ...   58                        23     0.156342   
1          0.04812  ...   58                        23     0.156342   
2          0.04812  ...   58                        23     0.156342   
3          0.04812  ...   58                        23     0.156342   
4          0.04812  ...   58                        23     0.156342   

   perc_alone  perc_walk  perc_other  2018_outflow  2019_outflow  \
0    0.638938   0.037168         0.0             0             0   
1    0.638938   0.037168         0.0             0             0   
2    0.638938   0.037168         0.0             0             0   
3    0.638938   0.037168         0.0             0             0   
4    0.638938   0.037168         0.0             0             0   

   2020_outflow  pred_outflow  
0             0            78  
1             0            78  
2             0            78  
3             0            78  
4             0            78  

[5 rows x 26 columns]

In [120]:
df.columns

Index(['total_households', 'median_hh_income', 'mean_hh_income',
       'population_16yrs+', 'in_labor_force', 'civ_labor_force', 'employed',
       'unemployed', 'perc_employed', 'perc_unemployed', 'Workers_16yrs+',
       'own_alone', 'carpool', 'public_transit', 'walked', 'other', 'wfh',
       'mean_travel_time_to_work', 'perc_public', 'perc_alone', 'perc_walk',
       'perc_other', '2018_outflow', '2019_outflow', '2020_outflow',
       'pred_outflow'],
      dtype='object')

In [121]:
for row in range(len(df)):
    for col in df.columns:
        if df.loc[row][col] == '-' or pd.isna(df.loc[row][col]):
            df.at[row,col] = 0

In [122]:
df = df.drop(columns=['median_hh_income','mean_hh_income','in_labor_force', 'civ_labor_force', 
                      'employed','unemployed', 'perc_employed', 'perc_unemployed','own_alone', 
                      'carpool', 'public_transit', 'walked', 'other', 'wfh','mean_travel_time_to_work', 
                      'perc_public', 'perc_alone', 'perc_walk','perc_other', '2018_outflow', '2019_outflow', '2020_outflow'])
df.head(4)

total_households  population_16yrs+  Workers_16yrs+  pred_outflow
0              1306               2660            1695            78
1              1306               2660            1695            78
2              1306               2660            1695            78
3              1306               2660            1695            78

In [123]:
X = df.iloc[:, 0:3].to_numpy()
y = df.iloc[:,3].to_numpy()

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=42)

In [124]:
reg = LinearRegression().fit(X_train, y_train)
reg.score(X_train, y_train)

0.07875031575762126

In [125]:
reg.coef_

array([-0.11701882,  0.12176365,  0.07343817])

In [126]:
reg.intercept_

99.95493761609404

In [127]:
y_pred = reg.predict(X_test).astype(int)

In [128]:
###calculate mean squared error
mean_absolute_error(y_test,y_pred)

244.44292237442923

In [129]:
y_pred

array([251, 968, 426, 754, 208, 181, 306,  99, 300, 220, 235, 294, 259,
       312, 307, 364, 218, 220, 348, 477, 284, 306, 298, 290, 355, 477,
       312, 128, 212, 237, 166, 277, 395, 324, 298, 259, 405, 405, 401,
       235, 100, 329, 329, 285, 550, 232, 275, 275, 267, 252, 481, 445,
       232, 282, 157, 312, 277, 344, 235, 670, 550, 277, 290, 267, 405,
       968, 178, 534,  99, 233, 237, 232, 466, 477, 361, 401, 324, 278,
       469, 332, 297, 273, 232, 355, 383, 235, 235, 361, 294, 312, 297,
       426, 481, 259, 259, 383, 235, 342, 267, 294, 178, 383, 100, 185,
       235, 670, 405, 304, 312, 252, 412, 477, 395, 252, 324, 154, 290,
       306, 275, 451, 285, 357, 235, 401, 166, 304, 252, 235, 626, 212,
       330, 968, 157, 477,  99, 534, 405, 477, 348, 491, 469, 534, 220,
       357, 968, 451, 235, 534, 312, 395, 426, 128, 157, 313, 481, 336,
       534, 269, 451, 251, 300, 285, 405, 235,  99, 968, 324, 232,  99,
       332, 270,  99, 220, 300, 259, 405, 361, 178,  99, 299, 29

In [130]:
y_true

array([ 207,    0,  327,  440,  440,  440,  440,  440, 1062,  250,  250,
        250,  250,  250,  250,  356,  354,  356, 2279, 1043, 1388,  856,
       1327, 2828, 1704,  998,  723,  497,  497,  796,  896,    0,    0,
          0,    0,    0,    0,  529,  188,  188,  188,  188,  188, 1962,
        376,  864,  929,  326,  326,  326,  326,    2,    2,    2,    2,
          2,    2, 1225,  725,  608,  608,  608,  608,  608, 1129, 1129,
       1129,  670,  561,  173,  173,  173,  169,  169,  169,  169,  169,
        169,  169,  169,  120,  120,  120,  120,  120,  120,  120,  120,
        120,  120,  120,  120,  120,  120,  120,  120,  622,  223,  388,
        197,  464,  464,  464,  464,  464,  464,  755, 1567,  555,  185,
        363,  245,  555,  892,  435,  435,  435,  435,  739,  997,  892,
       1034,  399,  399,  399,  497,  467,   41,   41,   41,   41,   41,
         41,   41,   41,   41,  424,  424,  424,  424, 1008,  828,  697,
        842,  530,  530,  530,  530,  367,  367,  3

In [131]:
len(y_pred)

219

In [132]:
len(y_test)

219